### ISSUE TITLE
In Playground, "Request failed with status code 500"

### ISSUE THREAD

**Issue by ganymedio** [operate-bsv/www.operatebsv.org#5]
At https://www.operatebsv.org/playground/ under Millionaire Maker, I put in my name and swiped and got an error 500 message.

Link to the transaction on WOC: 

https://whatsonchain.com/tx/5aee53dee235337144b0ca93f39929d3cec6e5d35b14abb5404a8333bbe0b059

Also tried with default name "Satoshi Nakamoto" and same message.

**Comment by libitx** [comment]
Thanks. I believe the API server there is still using the legacy BOB planaria... which is pretty much dead now.

I'll switch the API over to the newer Bitbus APIs asap.

**Comment by libitx** [comment]
@bitcoinappdev I've just deployed an update that uses the latest version of the agent and the latest bitbus api. I think this should fix the issue.
